import './globals.css';
import ThemeRegistry from '../components/ThemeRegistry';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Kelsa - Task Board App',
  description: 'Generated by Next.js',
  icons: {
    icon: '/kelsa.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
